import { Component, OnInit, Output, EventEmitter} from '@angular/core';

@Component({
  selector: 'todo-input',
  templateUrl: './input.component.html',
  styleUrls: ['./input.component.css']
})
export class InputComponent implements OnInit {

  title: string="My To Do List"

  constructor() { 
    console.log("inside the constructor")
    //this.changeTitle("I Love Angular") 
    console.log(this.title)
  }

@Output() submit: EventEmitter<string> = new EventEmitter();

 submitValue(newTitle: string): void {
   this.submit.emit(newTitle);
 }



generateTitle(): string {
  return 'This title was generated by a method.'
}

  ngOnInit() {
  }

}
